export const IMAGES = {
  heroBowl: require('../../assets/images/Hero_bowl.jpg'),
  aboutBowl: require('../../assets/images/About_bowl.jpg'),
  aboutChef: require('../../assets/images/About_chef.jpg'),
  serviceReadyMeals: require('../../assets/images/Service_ready_meals.jpg'),
  serviceCustomPlans: require('../../assets/images/Service_custom_plans.jpg'),
  serviceWeights: require('../../assets/images/Service_weights.jpg'),
  serviceWeight: require('../../assets/images/Service_weights.jpg'),
  serviceProtein: require('../../assets/images/Service_protein.jpg'),
  plansPromo: require('../../assets/images/Plans_promo.jpg'),
  ctaBg: require('../../assets/images/CTA_bg.jpg'),
  avatarSara: require('../../assets/images/Avatar_sara.jpg'),
  avatarAhmed: require('../../assets/images/Avatar_ahmed.jpg'),
  avatarFatima: require('../../assets/images/Avatar_fatima.jpg'),
} as const;